/**
 * iDeal Ghana - Comprehensive iPhone Catalog Dataset
 * Spans from iPhone 11 to iPhone 17 Pro Max with realistic Ghanaian market pricing (GHS)
 */
const IPHONE_CATALOG = [
  {
    id: "iphone-17-pro-max",
    name: "iPhone 17 Pro Max",
    series: "17",
    tag: "Next-Gen Flagship",
    badgeColor: "gold",
    condition: "Brand New (Boxed)",
    storage: "256GB",
    price: 24900,
    depositTier: 60, // Flagship 60%
    isFlagship: true,
    isZeroInterest: true,
    colorName: "Cosmic Titanium",
    colorHex: "#3e3b38",
    cameras: 3,
    hasDynamicIsland: true,
    screenSize: "6.9-inch OLED 120Hz",
    batteryHealth: "100%",
    chipset: "A19 Pro Bionic",
    features: ["Super Retina XDR", "Action Button", "Pro-Motion 120Hz", "USB-C 3.0", "Apple Intelligence Ready"],
    image: "assets/phones/iphone-17-pro-max.png"
  },
  {
    id: "iphone-17-pro",
    name: "iPhone 17 Pro",
    series: "17",
    tag: "Next-Gen Pro",
    badgeColor: "gold",
    condition: "Brand New (Boxed)",
    storage: "256GB",
    price: 22900,
    depositTier: 60,
    isFlagship: true,
    isZeroInterest: true,
    colorName: "Natural Titanium",
    colorHex: "#524f4a",
    cameras: 3,
    hasDynamicIsland: true,
    screenSize: "6.3-inch OLED 120Hz",
    batteryHealth: "100%",
    chipset: "A19 Pro Bionic",
    features: ["48MP Fusion Triple Camera", "Always-On Display", "Ceramic Shield 2", "USB-C"],
    image: "assets/phones/iphone-17-pro.png"
  },
  {
    id: "iphone-17",
    name: "iPhone 17",
    series: "17",
    tag: "Latest Standard",
    badgeColor: "blue",
    condition: "Brand New (Boxed)",
    storage: "128GB",
    price: 17500,
    depositTier: 60,
    isFlagship: true,
    isZeroInterest: true,
    colorName: "Ultramarine Blue",
    colorHex: "#3858c4",
    cameras: 2,
    hasDynamicIsland: true,
    screenSize: "6.2-inch OLED",
    batteryHealth: "100%",
    chipset: "A19 Chip",
    features: ["Camera Control Button", "48MP Dual System", "All-Day Battery", "Dynamic Island"],
    image: "assets/phones/iphone-17.png"
  },
  {
    id: "iphone-16-pro-max",
    name: "iPhone 16 Pro Max",
    series: "16",
    tag: "Best Seller Flagship",
    badgeColor: "gold",
    condition: "Brand New (Boxed)",
    storage: "256GB",
    price: 22500,
    depositTier: 60,
    isFlagship: true,
    isZeroInterest: true,
    colorName: "Desert Titanium",
    colorHex: "#c5ab8d",
    cameras: 3,
    hasDynamicIsland: true,
    screenSize: "6.9-inch Super Retina",
    batteryHealth: "100%",
    chipset: "A18 Pro Bionic",
    features: ["Camera Control", "4K 120 fps Dolby Vision", "Grade 5 Titanium", "5x Telephoto"],
    image: "assets/phones/iphone-16-pro-max.png"
  },
  {
    id: "iphone-16-pro",
    name: "iPhone 16 Pro",
    series: "16",
    tag: "Pro Compact",
    badgeColor: "gold",
    condition: "Brand New (Boxed)",
    storage: "128GB",
    price: 19800,
    depositTier: 60,
    isFlagship: true,
    isZeroInterest: true,
    colorName: "Black Titanium",
    colorHex: "#2b2a29",
    cameras: 3,
    hasDynamicIsland: true,
    screenSize: "6.3-inch Super Retina",
    batteryHealth: "100%",
    chipset: "A18 Pro Bionic",
    features: ["Studio-Quality 4-Mic Array", "ProMotion 120Hz", "USB 3 Speeds"],
    image: "assets/phones/iphone-16-pro.png"
  },
  {
    id: "iphone-16",
    name: "iPhone 16",
    series: "16",
    tag: "Hot Demand",
    badgeColor: "blue",
    condition: "Brand New (Boxed)",
    storage: "128GB",
    price: 15200,
    depositTier: 60,
    isFlagship: true,
    isZeroInterest: true,
    colorName: "Teal Green",
    colorHex: "#297775",
    cameras: 2,
    hasDynamicIsland: true,
    screenSize: "6.1-inch Super Retina",
    batteryHealth: "100%",
    chipset: "A18 Chip",
    features: ["Action Button", "Camera Control", "Spatial Photos", "Dynamic Island"],
    image: "assets/phones/iphone-16.png"
  },
  {
    id: "iphone-15-pro-max",
    name: "iPhone 15 Pro Max",
    series: "15",
    tag: "Ghana Favorite",
    badgeColor: "cyan",
    condition: "Gently Used (Grade A+)",
    storage: "256GB",
    price: 15900,
    depositTier: 40,
    isFlagship: false,
    isZeroInterest: true,
    colorName: "Blue Titanium",
    colorHex: "#353d4c",
    cameras: 3,
    hasDynamicIsland: true,
    screenSize: "6.7-inch OLED 120Hz",
    batteryHealth: "96% Battery",
    chipset: "A17 Pro",
    features: ["Titanium Chassis", "5x Optical Zoom", "Action Button", "USB-C Port"],
    image: "assets/phones/iphone-15-pro-max.png"
  },
  {
    id: "iphone-15-pro",
    name: "iPhone 15 Pro",
    series: "15",
    tag: "High Value",
    badgeColor: "cyan",
    condition: "Gently Used (Grade A+)",
    storage: "128GB",
    price: 13800,
    depositTier: 40,
    isFlagship: false,
    isZeroInterest: true,
    colorName: "Natural Titanium",
    colorHex: "#8f8a81",
    cameras: 3,
    hasDynamicIsland: true,
    screenSize: "6.1-inch OLED 120Hz",
    batteryHealth: "95% Battery",
    chipset: "A17 Pro",
    features: ["Super Retina XDR", "Ray Tracing Gaming", "Lightweight Build"],
    image: "assets/phones/iphone-15-pro.png"
  },
  {
    id: "iphone-15",
    name: "iPhone 15",
    series: "15",
    tag: "Everyday Master",
    badgeColor: "green",
    condition: "Brand New (Boxed)",
    storage: "128GB",
    price: 11900,
    depositTier: 40,
    isFlagship: false,
    isZeroInterest: false,
    colorName: "Matte Black",
    colorHex: "#222222",
    cameras: 2,
    hasDynamicIsland: true,
    screenSize: "6.1-inch OLED",
    batteryHealth: "100%",
    chipset: "A16 Bionic",
    features: ["Dynamic Island", "48MP Main Camera", "Color-infused Back Glass", "USB-C"],
    image: "assets/phones/iphone-15.png"
  },
  {
    id: "iphone-14-pro-max",
    name: "iPhone 14 Pro Max",
    series: "14",
    tag: "Accra Sensation",
    badgeColor: "purple",
    condition: "Gently Used (Grade A+)",
    storage: "128GB",
    price: 11500,
    depositTier: 40,
    isFlagship: false,
    isZeroInterest: false,
    colorName: "Deep Purple",
    colorHex: "#45384e",
    cameras: 3,
    hasDynamicIsland: true,
    screenSize: "6.7-inch OLED 120Hz",
    batteryHealth: "92% Battery",
    chipset: "A16 Bionic",
    features: ["Dynamic Island debut", "48MP Pro Sensor", "Stainless Steel Frame"],
    image: "assets/phones/iphone-14-pro-max.png"
  },
  {
    id: "iphone-14-pro",
    name: "iPhone 14 Pro",
    series: "14",
    tag: "Premium Deal",
    badgeColor: "purple",
    condition: "Gently Used (Grade A+)",
    storage: "128GB",
    price: 9900,
    depositTier: 40,
    isFlagship: false,
    isZeroInterest: false,
    colorName: "Space Black",
    colorHex: "#282828",
    cameras: 3,
    hasDynamicIsland: true,
    screenSize: "6.1-inch OLED 120Hz",
    batteryHealth: "91% Battery",
    chipset: "A16 Bionic",
    features: ["Always-On Screen", "ProMotion Display", "Cinematic 4K"],
    image: "assets/phones/iphone-14-pro.png"
  },
  {
    id: "iphone-14",
    name: "iPhone 14",
    series: "14",
    tag: "Student & Work Special",
    badgeColor: "blue",
    condition: "Gently Used (Grade A+)",
    storage: "128GB",
    price: 7900,
    depositTier: 40,
    isFlagship: false,
    isZeroInterest: false,
    colorName: "Midnight Blue",
    colorHex: "#1f2732",
    cameras: 2,
    hasDynamicIsland: false,
    screenSize: "6.1-inch Super Retina",
    batteryHealth: "93% Battery",
    chipset: "A15 Bionic (5-core GPU)",
    features: ["Crash Detection", "Photonic Engine", "TrueDepth Autofocus"],
    image: "assets/phones/iphone-14.png"
  },
  {
    id: "iphone-13-pro-max",
    name: "iPhone 13 Pro Max",
    series: "13",
    tag: "Battery Monster",
    badgeColor: "cyan",
    condition: "Gently Used (Grade A+)",
    storage: "128GB",
    price: 8500,
    depositTier: 40,
    isFlagship: false,
    isZeroInterest: false,
    colorName: "Sierra Blue",
    colorHex: "#698396",
    cameras: 3,
    hasDynamicIsland: false,
    screenSize: "6.7-inch OLED 120Hz",
    batteryHealth: "89% Battery",
    chipset: "A15 Bionic",
    features: ["Huge Battery Life", "Macro Photography", "ProMotion 120Hz"],
    image: "assets/phones/iphone-13-pro-max.png"
  },
  {
    id: "iphone-13-pro",
    name: "iPhone 13 Pro",
    series: "13",
    tag: "Compact Powerhouse",
    badgeColor: "cyan",
    condition: "Gently Used (Grade A+)",
    storage: "128GB",
    price: 7400,
    depositTier: 40,
    isFlagship: false,
    isZeroInterest: false,
    colorName: "Graphite",
    colorHex: "#393939",
    cameras: 3,
    hasDynamicIsland: false,
    screenSize: "6.1-inch OLED 120Hz",
    batteryHealth: "90% Battery",
    chipset: "A15 Bionic",
    features: ["Cinematic Mode", "Telephoto 3x", "Stainless Steel Frame"],
    image: "assets/phones/iphone-13-pro.png"
  },
  {
    id: "iphone-13",
    name: "iPhone 13",
    series: "13",
    tag: "Sweet Spot Value",
    badgeColor: "green",
    condition: "Gently Used (Grade A+)",
    storage: "128GB",
    price: 5900,
    depositTier: 40,
    isFlagship: false,
    isZeroInterest: false,
    colorName: "Starlight White",
    colorHex: "#f0ede6",
    cameras: 2,
    hasDynamicIsland: false,
    screenSize: "6.1-inch Super Retina",
    batteryHealth: "91% Battery",
    chipset: "A15 Bionic",
    features: ["Sensor-shift OIS", "HDR 4 Video", "MagSafe Wireless"],
    image: "assets/phones/iphone-13.png"
  },
  {
    id: "iphone-12-pro-max",
    name: "iPhone 12 Pro Max",
    series: "12",
    tag: "Pro Big Screen",
    badgeColor: "blue",
    condition: "Gently Used (Grade A+)",
    storage: "128GB",
    price: 5800,
    depositTier: 40,
    isFlagship: false,
    isZeroInterest: false,
    colorName: "Pacific Blue",
    colorHex: "#2b4c5e",
    cameras: 3,
    hasDynamicIsland: false,
    screenSize: "6.7-inch OLED",
    batteryHealth: "88% Battery",
    chipset: "A14 Bionic",
    features: ["LiDAR Scanner", "Apple ProRAW", "Dolby Vision HDR"],
    image: "assets/phones/iphone-12-pro-max.png"
  },
  {
    id: "iphone-12",
    name: "iPhone 12",
    series: "12",
    tag: "Affordable 5G",
    badgeColor: "blue",
    condition: "Gently Used (Grade A+)",
    storage: "128GB",
    price: 4200,
    depositTier: 40,
    isFlagship: false,
    isZeroInterest: false,
    colorName: "Ocean Blue",
    colorHex: "#1c3f60",
    cameras: 2,
    hasDynamicIsland: false,
    screenSize: "6.1-inch OLED",
    batteryHealth: "87% Battery",
    chipset: "A14 Bionic",
    features: ["Ceramic Shield Front", "Night Mode on all cameras", "5G Enabled"],
    image: "assets/phones/iphone-12.png"
  },
  {
    id: "iphone-11-pro-max",
    name: "iPhone 11 Pro Max",
    series: "11",
    tag: "Classic Triple Camera",
    badgeColor: "green",
    condition: "Gently Used (Grade A+)",
    storage: "64GB / 256GB",
    price: 4100,
    depositTier: 40,
    isFlagship: false,
    isZeroInterest: false,
    colorName: "Midnight Green",
    colorHex: "#37453f",
    cameras: 3,
    hasDynamicIsland: false,
    screenSize: "6.5-inch Super Retina XDR",
    batteryHealth: "86% Battery",
    chipset: "A13 Bionic",
    features: ["Matte Glass Back", "4K 60fps Video", "Deep Fusion Processing"],
    image: "assets/phones/iphone-11-pro-max.png"
  },
  {
    id: "iphone-11",
    name: "iPhone 11",
    series: "11",
    tag: "Budget Starter King",
    badgeColor: "green",
    condition: "Gently Used (Grade A+)",
    storage: "128GB",
    price: 3200,
    depositTier: 40,
    isFlagship: false,
    isZeroInterest: false,
    colorName: "Black",
    colorHex: "#1a1a1a",
    cameras: 2,
    hasDynamicIsland: false,
    screenSize: "6.1-inch Liquid Retina",
    batteryHealth: "86% Battery",
    chipset: "A13 Bionic",
    features: ["Ultra-wide Lens", "Night Mode", "Reliable All-Day Battery"],
    image: "assets/phones/iphone-11.png"
  },
  {
    id: "iphone-se-3",
    name: "iPhone SE (3rd Gen)",
    series: "SE",
    tag: "Entry Level Pocket",
    badgeColor: "orange",
    condition: "Gently Used (Grade A+)",
    storage: "64GB",
    price: 2700,
    depositTier: 40,
    isFlagship: false,
    isZeroInterest: false,
    colorName: "Midnight Black",
    colorHex: "#1b1e23",
    cameras: 1,
    hasDynamicIsland: false,
    screenSize: "4.7-inch Retina HD",
    batteryHealth: "95% Battery",
    chipset: "A15 Bionic",
    features: ["Touch ID Home Button", "A15 Fast Performance", "Super Compact Design"],
    image: "assets/phones/iphone-se.png"
  }
];

/**
 * Trade-In Estimation Matrix
 * Realistic baseline valuation in Ghanaian Cedis (GHS)
 */
const TRADE_IN_DEVICES = [
  { model: "iPhone 15 Pro Max", baseVal: 9500 },
  { model: "iPhone 15 Pro", baseVal: 8200 },
  { model: "iPhone 15 Plus", baseVal: 6800 },
  { model: "iPhone 15", baseVal: 6200 },
  { model: "iPhone 14 Pro Max", baseVal: 6500 },
  { model: "iPhone 14 Pro", baseVal: 5500 },
  { model: "iPhone 14", baseVal: 4200 },
  { model: "iPhone 13 Pro Max", baseVal: 4800 },
  { model: "iPhone 13 Pro", baseVal: 4000 },
  { model: "iPhone 13", baseVal: 3200 },
  { model: "iPhone 12 Pro Max", baseVal: 3300 },
  { model: "iPhone 12 Pro", baseVal: 2700 },
  { model: "iPhone 12", baseVal: 2200 },
  { model: "iPhone 11 Pro Max", baseVal: 2300 },
  { model: "iPhone 11 Pro", baseVal: 1900 },
  { model: "iPhone 11", baseVal: 1500 },
  { model: "iPhone XR / XS Max", baseVal: 1100 },
  { model: "Samsung S23 / S22 Series", baseVal: 2500 }
];
